//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int id { get; set; }
        public string teamOne { get; set; }
        public string teamTwo { get; set; }
        public Nullable<int> scoreOne { get; set; }
        public Nullable<int> scoreTwo { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
